[package]
name = "etc"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities"]
description = "API for reading etc/ files (UNIX)"

[dependencies]
regex = "1.11.0"
tempfile = "3.13.0"
thiserror = "2.0.0"

[[example]]
name = "read_hosts"

[[example]]
name = "read_services"