[package]
name = "lsof"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
thiserror = "2.0.0"
tokio = { version = "1.42.0", features = ["full"] }

[[example]]
name = "show_open_files"