
disk_file_path = "/Users/victormeyer/Dev/Self/rstracer/rstracer/test.duckdb"

[persist_layer]
bronze = true
silver = true
gold = true

[load_layer]
bronze = true
silver = true
gold = true

[vacuum]
bronze = 30
silver = 30
gold = 0

[schedule]
silver = 5
gold = 0
vacuum = 10

[request]
channel_size = 100
consumer_batch_size = 5

[ps]
channel_size = 300
producer_frequency = 2
consumer_batch_size = 100
