
disk_file_path = "rstracer.db"

[persist_layer]
bronze = true
silver = true
gold = true

[load_layer]
bronze = false
silver = false
gold = true

[vacuum]
bronze = 60
silver = 60
gold = 0

[schedule]
silver = 5
gold = 5
vacuum = 15
dimension = 300

[request]
channel_size = 100
consumer_batch_size = 10

[ps]
channel_size = 500
producer_frequency = 3
consumer_batch_size = 100

[lsof]
channel_size = 1000
producer_frequency = 15
consumer_batch_size = 200

[network]
channel_size = 200
consumer_batch_size = 25