
in_memory = false

[vacuum]
bronze = 15
silver = 15
gold = 0

[schedule]
silver = 5
gold = 5
vacuum = 15
dimension = 300

[request]
channel_size = 100
consumer_batch_size = 20

[ps]
channel_size = 500
producer_frequency = 3
consumer_batch_size = 200

[lsof]
channel_size = 1000
producer_frequency = 15
consumer_batch_size = 200

[network]
channel_size = 500
producer_frequency = 1
consumer_batch_size = 200