name: ci
'on':
  - pull_request
  - push
jobs:
  test-lib-debian:
    name: Test library On Debian
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x86
          - x86_64
          - arm
          - aarch64
        toolchain:
          - stable
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t rstracer-debian-image -f .docker/Dockerfile .
      - name: Test
        run: >
          container_id=$(docker run --privileged -d --mount type=bind,source=$(pwd),target=/rstracer/.coverage rstracer-debian-image)

          docker exec $container_id sh .docker/command.sh test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t rstracer-debian-image -f .docker/Dockerfile .
      - name: Lint
        run: >
          container_id=$(docker run --privileged -d --mount type=bind,source=$(pwd),target=/rstracer/.coverage rstracer-debian-image)

          docker exec $container_id sh .docker/command.sh lint
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t rstracer-debian-image -f .docker/Dockerfile .
      - name: Coverage
        run: >
          container_id=$(docker run --privileged -d --mount type=bind,source=$(pwd),target=/rstracer/.coverage rstracer-debian-image)

          docker exec $container_id sh .docker/command.sh coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: '${{ secrets.CODECOV_TOKEN }}'
